@HostAddress = http://localhost:8080

@UserIdSteff = beb28bb5-caac-4cf6-bdf3-db7485575c20
@BookingIdForSteff = 469c471b-8881-4aa3-9f1b-cb205f3f8c08

### API
GET {{HostAddress}}/

### Health check
GET {{HostAddress}}/health

### Apartments search
GET {{HostAddress}}/api/v1/apartments?startDate=2025-01-25&endDate=2025-01-27

### Apartments search INVALID (end date before start date)
GET {{HostAddress}}/api/v1/apartments?startDate=2025-01-25&endDate=2025-01-20

### User login
# @name token
POST {{HostAddress}}/api/v2/users/login
Content-Type: application/json

{
  "email": "steff@user.io",
  "password": "12345"
}

### Booking get
GET {{HostAddress}}/api/v1/bookings/{{BookingIdForSteff}}
Authorization: Bearer {{token.response.body.$.accessToken}}

### Booking reserve
POST {{HostAddress}}/api/v1/bookings
Authorization: Bearer {{token.response.body.$.accessToken}}
Content-Type: application/json

{
  "ApartmentId": "24331b4f-d70d-4d17-b528-e30e8829b1a6",
  "UserId": "{{UserIdSteff}}",
  "StartDate": "2025-01-25",
  "EndDate": "2025-01-27"
}

### Booking reject
PUT {{HostAddress}}/api/v1/bookings/60767b1f-2307-4e6f-85e3-72a32ed1937a/reject
Authorization: Bearer {{token.response.body.$.accessToken}}

### User register
POST {{HostAddress}}/api/v2/users/register
Content-Type: application/json

{
  "email": "steff@user.io",
  "firstName": "steff",
  "lastName": "user",
  "password": "12345"
}

### User current
GET {{HostAddress}}/api/v2/users/me
Authorization: Bearer {{token.response.body.$.accessToken}}

### 
