version: '3'
services:
  api:
    container_name: bookify-api-dev
    build:
      context: .
    volumes:
      # Mount the root folder to:
      - ..:/bookify:cached
    stdin_open: true # docker run -i
    tty: true # docker run -t
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: bookify-postgres
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: bookify-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@user.io'
      PGADMIN_DEFAULT_PASSWORD: 'hunter2'
    depends_on:
      - postgres
    ports:
      - "8080:80"
